// Generated by gencpp from file sixrobot_core_msgs/CloseCamera.msg
// DO NOT EDIT!


#ifndef SIXROBOT_CORE_MSGS_MESSAGE_CLOSECAMERA_H
#define SIXROBOT_CORE_MSGS_MESSAGE_CLOSECAMERA_H

#include <ros/service_traits.h>


#include <sixrobot_core_msgs/CloseCameraRequest.h>
#include <sixrobot_core_msgs/CloseCameraResponse.h>


namespace sixrobot_core_msgs
{

struct CloseCamera
{

typedef CloseCameraRequest Request;
typedef CloseCameraResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CloseCamera
} // namespace sixrobot_core_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sixrobot_core_msgs::CloseCamera > {
  static const char* value()
  {
    return "1067b4a7f008fe1ff4bd9668312773fd";
  }

  static const char* value(const ::sixrobot_core_msgs::CloseCamera&) { return value(); }
};

template<>
struct DataType< ::sixrobot_core_msgs::CloseCamera > {
  static const char* value()
  {
    return "sixrobot_core_msgs/CloseCamera";
  }

  static const char* value(const ::sixrobot_core_msgs::CloseCamera&) { return value(); }
};


// service_traits::MD5Sum< ::sixrobot_core_msgs::CloseCameraRequest> should match 
// service_traits::MD5Sum< ::sixrobot_core_msgs::CloseCamera > 
template<>
struct MD5Sum< ::sixrobot_core_msgs::CloseCameraRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sixrobot_core_msgs::CloseCamera >::value();
  }
  static const char* value(const ::sixrobot_core_msgs::CloseCameraRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sixrobot_core_msgs::CloseCameraRequest> should match 
// service_traits::DataType< ::sixrobot_core_msgs::CloseCamera > 
template<>
struct DataType< ::sixrobot_core_msgs::CloseCameraRequest>
{
  static const char* value()
  {
    return DataType< ::sixrobot_core_msgs::CloseCamera >::value();
  }
  static const char* value(const ::sixrobot_core_msgs::CloseCameraRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sixrobot_core_msgs::CloseCameraResponse> should match 
// service_traits::MD5Sum< ::sixrobot_core_msgs::CloseCamera > 
template<>
struct MD5Sum< ::sixrobot_core_msgs::CloseCameraResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sixrobot_core_msgs::CloseCamera >::value();
  }
  static const char* value(const ::sixrobot_core_msgs::CloseCameraResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sixrobot_core_msgs::CloseCameraResponse> should match 
// service_traits::DataType< ::sixrobot_core_msgs::CloseCamera > 
template<>
struct DataType< ::sixrobot_core_msgs::CloseCameraResponse>
{
  static const char* value()
  {
    return DataType< ::sixrobot_core_msgs::CloseCamera >::value();
  }
  static const char* value(const ::sixrobot_core_msgs::CloseCameraResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SIXROBOT_CORE_MSGS_MESSAGE_CLOSECAMERA_H
