// Generated by gencpp from file sixrobot_core_msgs/SolvePositionIK.msg
// DO NOT EDIT!


#ifndef SIXROBOT_CORE_MSGS_MESSAGE_SOLVEPOSITIONIK_H
#define SIXROBOT_CORE_MSGS_MESSAGE_SOLVEPOSITIONIK_H

#include <ros/service_traits.h>


#include <sixrobot_core_msgs/SolvePositionIKRequest.h>
#include <sixrobot_core_msgs/SolvePositionIKResponse.h>


namespace sixrobot_core_msgs
{

struct SolvePositionIK
{

typedef SolvePositionIKRequest Request;
typedef SolvePositionIKResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SolvePositionIK
} // namespace sixrobot_core_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sixrobot_core_msgs::SolvePositionIK > {
  static const char* value()
  {
    return "18cc92fd96853eb10b34de0b5c7d3cba";
  }

  static const char* value(const ::sixrobot_core_msgs::SolvePositionIK&) { return value(); }
};

template<>
struct DataType< ::sixrobot_core_msgs::SolvePositionIK > {
  static const char* value()
  {
    return "sixrobot_core_msgs/SolvePositionIK";
  }

  static const char* value(const ::sixrobot_core_msgs::SolvePositionIK&) { return value(); }
};


// service_traits::MD5Sum< ::sixrobot_core_msgs::SolvePositionIKRequest> should match 
// service_traits::MD5Sum< ::sixrobot_core_msgs::SolvePositionIK > 
template<>
struct MD5Sum< ::sixrobot_core_msgs::SolvePositionIKRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sixrobot_core_msgs::SolvePositionIK >::value();
  }
  static const char* value(const ::sixrobot_core_msgs::SolvePositionIKRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sixrobot_core_msgs::SolvePositionIKRequest> should match 
// service_traits::DataType< ::sixrobot_core_msgs::SolvePositionIK > 
template<>
struct DataType< ::sixrobot_core_msgs::SolvePositionIKRequest>
{
  static const char* value()
  {
    return DataType< ::sixrobot_core_msgs::SolvePositionIK >::value();
  }
  static const char* value(const ::sixrobot_core_msgs::SolvePositionIKRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sixrobot_core_msgs::SolvePositionIKResponse> should match 
// service_traits::MD5Sum< ::sixrobot_core_msgs::SolvePositionIK > 
template<>
struct MD5Sum< ::sixrobot_core_msgs::SolvePositionIKResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sixrobot_core_msgs::SolvePositionIK >::value();
  }
  static const char* value(const ::sixrobot_core_msgs::SolvePositionIKResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sixrobot_core_msgs::SolvePositionIKResponse> should match 
// service_traits::DataType< ::sixrobot_core_msgs::SolvePositionIK > 
template<>
struct DataType< ::sixrobot_core_msgs::SolvePositionIKResponse>
{
  static const char* value()
  {
    return DataType< ::sixrobot_core_msgs::SolvePositionIK >::value();
  }
  static const char* value(const ::sixrobot_core_msgs::SolvePositionIKResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SIXROBOT_CORE_MSGS_MESSAGE_SOLVEPOSITIONIK_H
